version: "3.8"
services:
  backend_doodle:
    build: 
      context: ./api/
      dockerfile: Dockerfile
    container-name: backend_doodle
    image: backend_doodle
    restart: on-failure
    environment:
      - quarkus.datasource.jdbc.url=jdbc:mysql://db:3306/tlc?useUnicode=true&serverTimezone=Europe/Paris
      - doodle.internalPadUrl=http://etherpad:9001/
      - doodle.externalPadUrl=http://pad.tufe.diverse-team.fr:8085/
    depends_on:
      - db
    links:
      - db
    ports :
      - "8080:8080"
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tlc
      - MYSQL_USER=tlc
      - MYSQL_PASSWORD=tlc
  etherpad:
    image: etherpad/etherpad:stable
    ports:
      - "9001:9001"
    volumes:
      - ./APIKEY.txt:/opt/etherpad-lite/APIKEY.txt
  mail:
    image: bytemark/smtp
    restart: always
    ports:
      - "2525:25" 
  frontend_doodle:
    build:
      context: ./front/
      dockerfile: Dockerfile
    container-name: frontend_doodle
    image: frontend_doodle
    depends_on:
      - proxy
  proxy:
    image: bunkerity/bunkerized-nginx
    restart: always
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - ./server-confs:/server-confs:ro
    environment:
      - SERVER_NAME=aamiard.diverse-team.fr
      - SERVE_FILES=no
      - DISABLE_DEFAULT_SERVER=no
      - PROXY_REAL_IP=yes
      - AUTO_LETS_ENCRYPT=yes
      - REDIRECT_HTTP_TO_HTTPS=yes
      - USE_LIMIT_REQ=no
      - HTTP2=no
      - FEATURE_POLICY=accelerometer 'none'; ambient-light-sensor 'none'; autoplay 'none'; camera 'none'; display-capture 'none'; document-domain 'none'; encrypted-media 'none'; fullscreen 'none'; geolocation 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; midi 'none'; payment 'none'; picture-in-picture 'none'; speaker 'none'; sync-xhr 'self'; usb 'none'; vibrate 'none'; vr 'none'
      - USE_REMOTE_API=no
